# Generated by Django 3.1.13 on 2021-09-16 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='student',
        ),
    ]
