# Generated by Django 3.1.13 on 2021-09-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('a', 'Available'), ('b', 'Borrowed')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
