# Generated by Django 3.1.13 on 2021-09-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Available', 'a'), ('Borrowed', 'b')], max_length=10),
        ),
    ]
