# Generated by Django 3.1.13 on 2021-09-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20210918_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
