# Generated by Django 3.1.13 on 2021-09-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20210921_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Available', 'a'), ('Borrowed', 'b')], default='Available', max_length=10),
        ),
    ]
