# Generated by Django 3.1.13 on 2021-09-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20210923_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.FileField(upload_to='book/images/'),
        ),
    ]
