# Generated by Django 3.1.13 on 2021-09-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20210924_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='book/images/'),
        ),
    ]
