# Generated by Django 3.1.13 on 2021-09-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_auto_20210927_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(null=True, upload_to='book/images/'),
        ),
    ]
