# Generated by Django 3.1.13 on 2021-09-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(blank=True, default='student/images/profile.jpg', null=True, upload_to='student/images/'),
        ),
    ]
