# Generated by Django 3.1.13 on 2021-09-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210923_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(blank=True, default='../static/accounts/images/profile.jpg', null=True, upload_to='student/images/'),
        ),
    ]
