# Generated by Django 3.1.13 on 2021-09-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210923_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(default='static/accounts/images/profile.jpg', upload_to='student/images/'),
        ),
    ]
